//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5477
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ncresponse {
    
    private uint orderIDField;
    
    private uint pAYIDField;
    
    private byte nCSTATUSField;
    
    private byte nCERRORField;
    
    private string aCCEPTANCEField;
    
    private byte sTATUSField;
    
    private byte iPCTYField;
    
    private byte cCCTYField;
    
    private byte eCIField;
    
    private string cVCCheckField;
    
    private string aAVCheckField;
    
    private string vcField;
    
    private string aAVZIPField;
    
    private string aAVADDRESSField;
    
    private string aAVNAMEField;
    
    private string aAVPHONEField;
    
    private string aAVMAILField;
    
    private decimal amountField;
    
    private string currencyField;
    
    private string pmField;
    
    private string bRANDField;
    
    private string aLIASField;
    
    private string eCOM_BILLTO_POSTAL_CITYField;
    
    private string eCOM_BILLTO_POSTAL_COUNTRYCODEField;
    
    private string eCOM_BILLTO_POSTAL_STATEDESCField;
    
    private string eCOM_BILLTO_POSTAL_STREET_LINE1Field;
    
    private string eCOM_BILLTO_POSTAL_STREET_LINE2Field;
    
    private string eCOM_BILLTO_POSTAL_POSTALCODEField;
    
    private string cnField;
    
    private string eCOM_BILLTO_POSTAL_NAME_LASTField;
    
    private string eCOM_BILLTO_POSTAL_NAME_FIRSTField;
    
    private string eCOM_BILLTO_TELECOM_PHONE_NUMBERField;
    
    private string eCOM_SHIPTO_POSTAL_CITYField;
    
    private string eCOM_SHIPTO_POSTAL_COUNTRYCODEField;
    
    private string eCOM_SHIPTO_POSTAL_STATEDESCField;
    
    private string eCOM_SHIPTO_POSTAL_STREET_LINE1Field;
    
    private string eCOM_SHIPTO_POSTAL_STREET_LINE2Field;
    
    private string eCOM_SHIPTO_POSTAL_POSTALCODEField;
    
    private string eCOM_SHIPTO_POSTAL_NAME_LASTField;
    
    private string nCERRORPLUSField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint orderID {
        get {
            return this.orderIDField;
        }
        set {
            this.orderIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint PAYID {
        get {
            return this.pAYIDField;
        }
        set {
            this.pAYIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte NCSTATUS {
        get {
            return this.nCSTATUSField;
        }
        set {
            this.nCSTATUSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte NCERROR {
        get {
            return this.nCERRORField;
        }
        set {
            this.nCERRORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ACCEPTANCE {
        get {
            return this.aCCEPTANCEField;
        }
        set {
            this.aCCEPTANCEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte STATUS {
        get {
            return this.sTATUSField;
        }
        set {
            this.sTATUSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte IPCTY {
        get {
            return this.iPCTYField;
        }
        set {
            this.iPCTYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte CCCTY {
        get {
            return this.cCCTYField;
        }
        set {
            this.cCCTYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte ECI {
        get {
            return this.eCIField;
        }
        set {
            this.eCIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CVCCheck {
        get {
            return this.cVCCheckField;
        }
        set {
            this.cVCCheckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AAVCheck {
        get {
            return this.aAVCheckField;
        }
        set {
            this.aAVCheckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VC {
        get {
            return this.vcField;
        }
        set {
            this.vcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AAVZIP {
        get {
            return this.aAVZIPField;
        }
        set {
            this.aAVZIPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AAVADDRESS {
        get {
            return this.aAVADDRESSField;
        }
        set {
            this.aAVADDRESSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AAVNAME {
        get {
            return this.aAVNAMEField;
        }
        set {
            this.aAVNAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AAVPHONE {
        get {
            return this.aAVPHONEField;
        }
        set {
            this.aAVPHONEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string AAVMAIL {
        get {
            return this.aAVMAILField;
        }
        set {
            this.aAVMAILField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PM {
        get {
            return this.pmField;
        }
        set {
            this.pmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BRAND {
        get {
            return this.bRANDField;
        }
        set {
            this.bRANDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ALIAS {
        get {
            return this.aLIASField;
        }
        set {
            this.aLIASField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_BILLTO_POSTAL_CITY {
        get {
            return this.eCOM_BILLTO_POSTAL_CITYField;
        }
        set {
            this.eCOM_BILLTO_POSTAL_CITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_BILLTO_POSTAL_COUNTRYCODE {
        get {
            return this.eCOM_BILLTO_POSTAL_COUNTRYCODEField;
        }
        set {
            this.eCOM_BILLTO_POSTAL_COUNTRYCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_BILLTO_POSTAL_STATEDESC {
        get {
            return this.eCOM_BILLTO_POSTAL_STATEDESCField;
        }
        set {
            this.eCOM_BILLTO_POSTAL_STATEDESCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_BILLTO_POSTAL_STREET_LINE1 {
        get {
            return this.eCOM_BILLTO_POSTAL_STREET_LINE1Field;
        }
        set {
            this.eCOM_BILLTO_POSTAL_STREET_LINE1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_BILLTO_POSTAL_STREET_LINE2 {
        get {
            return this.eCOM_BILLTO_POSTAL_STREET_LINE2Field;
        }
        set {
            this.eCOM_BILLTO_POSTAL_STREET_LINE2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_BILLTO_POSTAL_POSTALCODE {
        get {
            return this.eCOM_BILLTO_POSTAL_POSTALCODEField;
        }
        set {
            this.eCOM_BILLTO_POSTAL_POSTALCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CN {
        get {
            return this.cnField;
        }
        set {
            this.cnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_BILLTO_POSTAL_NAME_LAST {
        get {
            return this.eCOM_BILLTO_POSTAL_NAME_LASTField;
        }
        set {
            this.eCOM_BILLTO_POSTAL_NAME_LASTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_BILLTO_POSTAL_NAME_FIRST {
        get {
            return this.eCOM_BILLTO_POSTAL_NAME_FIRSTField;
        }
        set {
            this.eCOM_BILLTO_POSTAL_NAME_FIRSTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_BILLTO_TELECOM_PHONE_NUMBER {
        get {
            return this.eCOM_BILLTO_TELECOM_PHONE_NUMBERField;
        }
        set {
            this.eCOM_BILLTO_TELECOM_PHONE_NUMBERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_SHIPTO_POSTAL_CITY {
        get {
            return this.eCOM_SHIPTO_POSTAL_CITYField;
        }
        set {
            this.eCOM_SHIPTO_POSTAL_CITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_SHIPTO_POSTAL_COUNTRYCODE {
        get {
            return this.eCOM_SHIPTO_POSTAL_COUNTRYCODEField;
        }
        set {
            this.eCOM_SHIPTO_POSTAL_COUNTRYCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_SHIPTO_POSTAL_STATEDESC {
        get {
            return this.eCOM_SHIPTO_POSTAL_STATEDESCField;
        }
        set {
            this.eCOM_SHIPTO_POSTAL_STATEDESCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_SHIPTO_POSTAL_STREET_LINE1 {
        get {
            return this.eCOM_SHIPTO_POSTAL_STREET_LINE1Field;
        }
        set {
            this.eCOM_SHIPTO_POSTAL_STREET_LINE1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_SHIPTO_POSTAL_STREET_LINE2 {
        get {
            return this.eCOM_SHIPTO_POSTAL_STREET_LINE2Field;
        }
        set {
            this.eCOM_SHIPTO_POSTAL_STREET_LINE2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_SHIPTO_POSTAL_POSTALCODE {
        get {
            return this.eCOM_SHIPTO_POSTAL_POSTALCODEField;
        }
        set {
            this.eCOM_SHIPTO_POSTAL_POSTALCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ECOM_SHIPTO_POSTAL_NAME_LAST {
        get {
            return this.eCOM_SHIPTO_POSTAL_NAME_LASTField;
        }
        set {
            this.eCOM_SHIPTO_POSTAL_NAME_LASTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string NCERRORPLUS {
        get {
            return this.nCERRORPLUSField;
        }
        set {
            this.nCERRORPLUSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
